/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocanproject;
　
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Font;
import javax.swing.JFrame;
public class ChocAnOperatorTerminal extends javax.swing.JFrame {
　
    
//URL for connecting to database
private final String connectionUrl = "jdbc:sqlserver://PRADEEP-PC\\PRADEEP-PC\\PJ:60665;databaseName=ChocAn;user=ChocAnUser;password=pass1234;";
//Flag to indicate Interactive Record Mode has been entered
private boolean interactiveRecordMode=false;
　
    /**
     * Creates new form MainGUIInterface
     */
    public ChocAnOperatorTerminal() {
        initComponents();
    }
　
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
　
        MainPanel = new javax.swing.JPanel();
        CommandDisplayArea = new javax.swing.JTextField();
        TerminalScrollPane = new javax.swing.JScrollPane();
        DataEntryArea = new javax.swing.JTextArea();
        EnterButton = new javax.swing.JButton();
        Enter_New_Service_Button = new javax.swing.JButton();
        Interactive_Record_Mode_Button = new javax.swing.JButton();
        CalculateWeeklyButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
　
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(166, 83, 0));
　
        MainPanel.setBackground(new java.awt.Color(166, 83, 0));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setToolTipText("");
　
        CommandDisplayArea.setEditable(false);
        CommandDisplayArea.setBackground(new java.awt.Color(5, 183, 250));
        CommandDisplayArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
　
        DataEntryArea.setBackground(new java.awt.Color(5, 183, 250));
        DataEntryArea.setColumns(20);
        DataEntryArea.setRows(5);
        DataEntryArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DataEntryArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DataEntryAreaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DataEntryAreaKeyTyped(evt);
            }
        });
        TerminalScrollPane.setViewportView(DataEntryArea);
　
        EnterButton.setText("Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });
　
        Enter_New_Service_Button.setText("Enter New Service");
　
        Interactive_Record_Mode_Button.setText("Interactive Record Mode");
        Interactive_Record_Mode_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Interactive_Record_Mode_ButtonActionPerformed(evt);
            }
        });
　
        CalculateWeeklyButton.setText("Calculate Weekly Fee");
        CalculateWeeklyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateWeeklyButtonActionPerformed(evt);
            }
        });
　
        jButton1.setText("Get Member Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
　
        jButton2.setText("Get Provider Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
　
        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CommandDisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(EnterButton)
                                .addGap(275, 275, 275))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(TerminalScrollPane)
                                .addGap(45, 45, 45)))
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Enter_New_Service_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Interactive_Record_Mode_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CalculateWeeklyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(79, 79, 79))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CommandDisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(Interactive_Record_Mode_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Enter_New_Service_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CalculateWeeklyButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(TerminalScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EnterButton)
                .addContainerGap(107, Short.MAX_VALUE))
        );
　
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
　
        pack();
    }// </editor-fold>//GEN-END:initComponents
　
    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        // TODO add your handling code here:
    
        //If interactive record mode has been entered     
        if(interactiveRecordMode){           
            String input = DataEntryArea.getText();
            if(!isValidModeSymbol(input))
                return;
            CommandDisplayArea.setFont(new Font(null,Font.PLAIN,12));
             if(input.equalsIgnoreCase("mi"))
          CommandDisplayArea.setText("Inserting member record");
      else if (input.equalsIgnoreCase("mu"))
          CommandDisplayArea.setText("Updating member record");
      else if (input.equalsIgnoreCase("md"))
          CommandDisplayArea.setText("Deleting member record");
      else if (input.equalsIgnoreCase("pi"))
          CommandDisplayArea.setText("Inserting provider record");
      else if (input.equalsIgnoreCase("pu"))
          CommandDisplayArea.setText("Updating provider record");
      else if (input.equalsIgnoreCase("pd"))
          CommandDisplayArea.setText("Deleting provider record");
      else 
          CommandDisplayArea.setText("");
            interactiveRecordMode = false;
        }     
        
    }//GEN-LAST:event_EnterButtonActionPerformed
　
    private void Interactive_Record_Mode_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Interactive_Record_Mode_ButtonActionPerformed
        // TODO add your handling code here:
        //String asking for which option they want to select and is displayed on the top text area
       //Found default code at https://docs.oracle.com/javase/8/docs/api/javax/swing/JFrame.html#setDefaultCloseOperation-int-
      InteractiveRecordMode InteractiveGUI = new InteractiveRecordMode();
      InteractiveGUI.setVisible(true);
      InteractiveGUI.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_Interactive_Record_Mode_ButtonActionPerformed
　
    private void DataEntryAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DataEntryAreaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataEntryAreaKeyPressed
　
    private void DataEntryAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DataEntryAreaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DataEntryAreaKeyTyped
　
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MemberReportGUI memberReport = new MemberReportGUI();
       memberReport.setVisible(true);
       memberReport.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed
　
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ProviderReportGUI providerReport = new ProviderReportGUI();
       providerReport.setVisible(true);
       providerReport.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed
　
    private void CalculateWeeklyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateWeeklyButtonActionPerformed
        // TODO add your handling code here:
        CalculateWeeklyFeeGUI calculateFee = new CalculateWeeklyFeeGUI();
       calculateFee.setVisible(true);
       calculateFee.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_CalculateWeeklyButtonActionPerformed
　
    private boolean isValidModeSymbol(String symbol){
        String str = symbol.trim();
        return str.equalsIgnoreCase("mi")||str.equalsIgnoreCase("mu")||str.equalsIgnoreCase("md")||str.equalsIgnoreCase("pi")||str.equalsIgnoreCase("pu")||str.equalsIgnoreCase("pd");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChocAnOperatorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChocAnOperatorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChocAnOperatorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChocAnOperatorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
　
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               ChocAnOperatorTerminal main_gui = new ChocAnOperatorTerminal();
               main_gui.setVisible(true);
               main_gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });
    }
　
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateWeeklyButton;
    private javax.swing.JTextField CommandDisplayArea;
    private javax.swing.JTextArea DataEntryArea;
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton Enter_New_Service_Button;
    private javax.swing.JButton Interactive_Record_Mode_Button;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane TerminalScrollPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
　
