/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
<<<<<<< HEAD
package csc640project;

=======
package chocanproject;
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
<<<<<<< HEAD

=======
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
/**
 *
 * @author Alex
 */
public class DeleteMemberGUI extends javax.swing.JFrame {
<<<<<<< HEAD
private final String connectionUrl = "jdbc:sqlserver://cscsql2.carrollu.edu;" +  
					   "databaseName=csc550_fall2015_akoltun;user=csc550_fall2015_akoltun;password=480772;";

=======
private final String connectionUrl = "jdbc:sqlserver://PRADEEP-PC\\PRADEEP-PC\\PJ:60665;databaseName=ChocAn;user=ChocAnUser;password=pass1234;";
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
    /**
     * Creates new form DeleteMemberGUI
     */
    public DeleteMemberGUI() {
        initComponents();
        setUpMenu();
    }
<<<<<<< HEAD

=======
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
<<<<<<< HEAD

=======
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
        MainPanel = new javax.swing.JPanel();
        MemberChoice = new java.awt.Choice();
        DeleteButton = new javax.swing.JButton();
        MemberIDLabel = new javax.swing.JLabel();
<<<<<<< HEAD

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(166, 83, 0));

=======
　
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
　
        MainPanel.setBackground(new java.awt.Color(166, 83, 0));
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
<<<<<<< HEAD

        MemberIDLabel.setText("MemberID");

=======
　
        MemberIDLabel.setText("MemberID");
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(MemberIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MemberChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(DeleteButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MemberChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemberIDLabel))
                .addGap(22, 22, 22)
                .addComponent(DeleteButton)
                .addContainerGap(93, Short.MAX_VALUE))
        );
<<<<<<< HEAD

=======
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
<<<<<<< HEAD

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Execution of when the delete button is clicked
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        //Delete the member with the given member id
        try {
        Connection con = DriverManager.getConnection(connectionUrl);
        Statement statement = con.createStatement();
       String sql = "Delete FROM Member WHERE MemberID = "+MemberChoice.getSelectedItem();
       statement.executeUpdate(sql);
=======
　
        pack();
    }// </editor-fold>//GEN-END:initComponents
　
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        try {
        
        Connection con = DriverManager.getConnection(connectionUrl);
        
        Statement statement = con.createStatement();
       String sql = "Delete FROM Member WHERE MemberID = "+MemberChoice.getSelectedItem();
       statement.executeUpdate(sql);
	
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
	con.close();
        this.setVisible(false);
			
    } catch (SQLException ex) {
<<<<<<< HEAD
        Logger.getLogger(MainGUIInterface.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_DeleteButtonActionPerformed
       
    //Set up the menu with the different member ids
     private void setUpMenu(){
         //Add members with select ids
        try {
        Connection con = DriverManager.getConnection(connectionUrl);
=======
        Logger.getLogger(ChocAnOperatorTerminal.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_DeleteButtonActionPerformed
　
     private void setUpMenu(){
        
        try {
        
        Connection con = DriverManager.getConnection(connectionUrl);
        
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
        Statement statement = con.createStatement();
       String query = "SELECT * FROM Member";
       ResultSet resultSet = statement.executeQuery(query);
	while(resultSet.next()){
	MemberChoice.add(resultSet.getString("MemberID"));
	 }
	con.close();
<<<<<<< HEAD
        //Close and hide the window
       this.setVisible(false);
    } catch (SQLException ex) {
        Logger.getLogger(MainGUIInterface.class.getName()).log(Level.SEVERE, null, ex);
=======
       this.setVisible(false);
    } catch (SQLException ex) {
        Logger.getLogger(ChocAnOperatorTerminal.class.getName()).log(Level.SEVERE, null, ex);
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
    }
   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
<<<<<<< HEAD

=======
        //</editor-fold>
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteMemberGUI().setVisible(true);
            }
        });
    }
<<<<<<< HEAD

=======
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JPanel MainPanel;
    private java.awt.Choice MemberChoice;
    private javax.swing.JLabel MemberIDLabel;
    // End of variables declaration//GEN-END:variables
}
<<<<<<< HEAD
=======
　
>>>>>>> 62e1ffe9d592baa80b0e11b3c8c167534daf691f
