/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocanproject;
　
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
　
/**
 *
 * @author Pradeep
 */
public class LookUpServiceGUI extends javax.swing.JFrame {
private final String connectionUrl = "jdbc:sqlserver://PRADEEP-PC\\PRADEEP-PC\\PJ:60665;databaseName=ChocAn;user=ChocAnUser;password=pass1234;";
  
    /**
     * Creates new form LookUpServiceGUI
     */
    public LookUpServiceGUI() {
        initComponents();
        ServiceCodeField.setText("");
    }
    private boolean lengthValidation(){
        if(ServiceCodeField.getText().length()>9&&ServiceCodeField.getText().length()<0){
            JOptionPane.showMessageDialog(null, "Service Code must between 1-9 ");
            return false;           
        }
        if(anyFieldsEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a Service Code ");
        
        return false;
    }
        if(!isNumeric(ServiceCodeField.getText())){
            JOptionPane.showMessageDialog(null,"Service code needs to be numeric");
            return false;
        }
        return true;
     }
    //Check if any fields are empty
    private boolean anyFieldsEmpty(){
        boolean serviceCode = ServiceCodeField.getText().trim().equals("");
        return serviceCode;
    }
    
    private boolean isNumeric(String s){
          try{
              Integer.parseInt(s);
          }
          catch(NumberFormatException e){
              return false;
          }
          
          return true;
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
　
        jLabel1 = new javax.swing.JLabel();
        ServiceCodeField = new javax.swing.JTextField();
        CheckServiceNameButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServiceDisplayTextArea = new javax.swing.JTextArea();
　
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
　
        jLabel1.setText("Enter Service Code");
　
        ServiceCodeField.setText("ServiceCode");
        ServiceCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceCodeFieldActionPerformed(evt);
            }
        });
        ServiceCodeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ServiceCodeFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ServiceCodeFieldKeyTyped(evt);
            }
        });
　
        CheckServiceNameButton.setText("Check for Service Name");
        CheckServiceNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckServiceNameButtonActionPerformed(evt);
            }
        });
　
        ServiceDisplayTextArea.setColumns(20);
        ServiceDisplayTextArea.setRows(5);
        jScrollPane1.setViewportView(ServiceDisplayTextArea);
　
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(ServiceCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(CheckServiceNameButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ServiceCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(CheckServiceNameButton)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
　
        pack();
    }// </editor-fold>//GEN-END:initComponents
　
    private void CheckServiceNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckServiceNameButtonActionPerformed
        // TODO add your handling code here:
        if(!lengthValidation()){
        return;
        }
        try {
            Connection con = DriverManager.getConnection(connectionUrl);
            //Generate report and set up prepared statement
            String sql = "EXECUTE ValidateService_Select ?";
            PreparedStatement prest = con.prepareStatement(sql);
            int sc = Integer.parseInt(ServiceCodeField.getText());
            prest.setInt(1, sc);
            ResultSet resultSet = prest.executeQuery();
            resultSet.next();
            ServiceDisplayTextArea.setText(resultSet.getString(1));
            con.close();
        }        catch (SQLException ex) {
            Logger.getLogger(ChocAnOperatorTerminal.class.getName()).log(Level.SEVERE, null, ex);
        }                          
    }//GEN-LAST:event_CheckServiceNameButtonActionPerformed
　
    private void ServiceCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceCodeFieldActionPerformed
　
    private void ServiceCodeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ServiceCodeFieldKeyPressed
        // TODO add your handling code here:
       int key=evt.getKeyCode();
       int number1 =  ServiceCodeField.getText().length();
       if(number1>9){      
           JOptionPane.showMessageDialog(null, "Provider number must be between 1-9 ");
       }             
    }//GEN-LAST:event_ServiceCodeFieldKeyPressed
　
    private void ServiceCodeFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ServiceCodeFieldKeyTyped
        // TODO add your handling code here:      
          char c = evt.getKeyChar();
          if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))
          evt.consume();
    }//GEN-LAST:event_ServiceCodeFieldKeyTyped
　
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LookUpServiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LookUpServiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LookUpServiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LookUpServiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
　
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LookUpServiceGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckServiceNameButton;
    private javax.swing.JTextField ServiceCodeField;
    private javax.swing.JTextArea ServiceDisplayTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
　
