/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocanproject;
　
import javax.swing.JFrame;
　
/**
 *
 * @author Pradeep
 */
public class ManagerTerminal extends javax.swing.JFrame {
　
    /**
     * Creates new form ManagerTerminal
     */
    public ManagerTerminal() {
        initComponents();
    }
　
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
　
        SummaryReportButton = new javax.swing.JButton();
        TotalSummaryReportButton = new javax.swing.JButton();
　
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
　
        SummaryReportButton.setText("Get Summary Report of  Providers to be Paid");
        SummaryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryReportButtonActionPerformed(evt);
            }
        });
　
        TotalSummaryReportButton.setText("Get Total Summary Report of all Providers");
        TotalSummaryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalSummaryReportButtonActionPerformed(evt);
            }
        });
　
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SummaryReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalSummaryReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(SummaryReportButton)
                .addGap(66, 66, 66)
                .addComponent(TotalSummaryReportButton)
                .addContainerGap(111, Short.MAX_VALUE))
        );
　
        pack();
    }// </editor-fold>//GEN-END:initComponents
　
    private void SummaryReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryReportButtonActionPerformed
        // TODO add your handling code here:
       SummaryReports summaryReports = new SummaryReports();
       summaryReports.setVisible(true);
       summaryReports.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); 
    }//GEN-LAST:event_SummaryReportButtonActionPerformed
　
    private void TotalSummaryReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalSummaryReportButtonActionPerformed
        // TODO add your handling code here:
       TotalSummaryReport totalsummaryReport = new TotalSummaryReport();
       totalsummaryReport.setVisible(true);
       totalsummaryReport.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); 
    }//GEN-LAST:event_TotalSummaryReportButtonActionPerformed
　
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
　
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerTerminal().setVisible(true);
            }
        });
    }
　
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SummaryReportButton;
    private javax.swing.JButton TotalSummaryReportButton;
    // End of variables declaration//GEN-END:variables
}
　
